#url: http://samplewebsite.github.io
#baseurl: http://samplewebsite.github.io

# Site settings
title: School
email: contact@mysds.in
description: "Official Website of School"


# Team names, titles and social links
people:
- name: Rishab bansal
  pic: 1
  position: Chairman
  social:
    - title: facebook
     # url: https://www.facebook.com/profile.php?id=100009702091351

- name: R.K.Bansal
  pic: 2
  position: Director
  social:
    - title: facebook
      #url: https://www.facebook.com/rjain1806?

- name: DR.R.Bansal
  pic: 3
  position: Principal
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    #url: https://twitter.com/schoolsds
  - title: facebook
    #url: https://www.facebook.com/sdsgzb/
    
# Postal address (add as many lines as necessary)
address:
  - line: 2, Laksar
  - line: Haridwar

# Build settings
markdown: kramdown
permalink: pretty
