url: http://rishabbansal.github.io
baseurl: http://rishabbansal.github.io

# Site settings
title: Spring Dale School
email: contact@mysds.in
description: "Official Website of Spring Dale School"


# Team names, titles and social links
people:
- name: Sh. Nem Chand Jain
  pic: 1
  position: Chairman
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100009702091351

- name: Sh. Rakesh Jain
  pic: 2
  position: Director
  social:
    - title: facebook
      url: https://www.facebook.com/rjain1806?

- name: Smt. Renu Jain
  pic: 3
  position: Principal
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/schoolsds
  - title: facebook
    url: https://www.facebook.com/sdsgzb/
    
# Postal address (add as many lines as necessary)
address:
  - line: 2, Gautam Nagar
  - line: Meerut Road, Ghaziabad

# Build settings
markdown: kramdown
permalink: pretty
